# Data configs
domainA_dir: '/Users/hasnainraza/Downloads/FacesProcessed/trainA'
domainB_dir: '/Users/hasnainraza/Downloads/FacesProcessed/trainB'

# Network Configs
ngf: 64
ndf: 64
n_blocks: 4
n_layers: 7

# Loss configs:
adv_weight: 1
cycle_weight: 10
identity_weight: 10
cam_weight: 1000

# Optimizer configs:
lr: 0.0001
weight_decay: 0.0001

# Training configs:
img_size: 256
batch_size: 4
num_workers: 4
epochs: 100
gpus: null